### ISSUE TITLE
Multiple datasets, metadata, workflows, and reproducibility

### ISSUE THREAD

**Issue by jpivarski** [HSF/PyHEP.dev-workshops#4]
Coordinating large-scale analysis steps in efficient and reproducible data pipelines, with systematics, different backgrounds, signals, data from different epochs, etc., as well as leveraging analysis facilities.

**Comment by maxgalli** [comment]
+1

**Comment by btovar** [comment]
+1

**Comment by btovar** [comment]
+1

**Comment by mattbellis** [comment]
+1 I think this is an under-discussed aspect of analysis flow and I am very interested in participating in the discussion.

**Comment by ianna** [comment]
+1

**Comment by pfackeldey** [comment]
+1

**Comment by kjvbrt** [comment]
+1

**Comment by jonas-eschle** [comment]
Interested too, and one thing to throw in that bothers me since a long time and seems to be missing: how to *modify* a dataset, reasonably? Sure, we shouldn't. Sure, spacewise inefficient. Sure. But I think this is very often needed in any prototyping phase of the analysis where we would like to just modify, try again, modify (no matter if it takes more space etc) instead of copying everything over. Say in a ROOT file, how to replace a branch (yep, aware of technical challenges in terms of memory layout etc, but the need from the user side still stands)?

More general, how can I manage a) a single filename and b) being able to easily replace single columns (this can be multiple files hidden, or whatever, I just never came across a decent solution)

**Comment by nikoladze** [comment]
+1

**Comment by matthewfeickert** [comment]
+1

**Comment by riga** [comment]
+1

**Comment by oshadura** [comment]
+1
