### ISSUE TITLE
User experience for physics data analysis tools

### ISSUE THREAD

**Issue by oshadura** [HSF/PyHEP.dev-workshops#9]
Various topics about how to make the life of physicists easier, tools interoperability and etc.

**Comment by jpivarski** [comment]
Question about overlap: is this included within #3, "expressing data analysis steps intuitively, to reduce cognitive burden"?

Group #3 is also about performance, which is a distinct topic from user experience, easy to read/write/understand analysis code, etc. At first, I was thinking of making them separate groups, but then decided to put them together because I wanted the people who are interested in these two things to be in the same conversation. If the "easy to use" crowd isn't talking to the "runs fast" crowd, then they'll develop two different ways of doing analysis, which is a disservice for users. (They'd get started on "the easy way" and then have to replace it all with "the fast way.")

**Comment by alexander-held** [comment]
#3 to me sounds like it is focused on orchestration and workflow management. I think there are UX aspects beyond "readability and performance": documentation, availability of examples, support mechanisms, intuitiveness of API, ease of interoperability between packages, missing features or functionality in the ecosystem (space for new libraries / frameworks).

**Comment by gordonwatts** [comment]
Definitely interested in this group!

**Comment by vgvassilev** [comment]
+1

**Comment by ccochato** [comment]
+1

**Comment by mattbellis** [comment]
+1

**Comment by ph-ilten** [comment]
+1 My main interests here are:
1. What is the general user experience for `Pythia8` (both C++ and Python), and how can we make it better?
2. Our documentation is extensive, but uses a rather outdated methodology. What kind of best practice exists, keeping in mind that we want stability on the order of decades?

**Comment by ianna** [comment]
+1

**Comment by matthewfeickert** [comment]
+1
